### Question 1

We must apply the k mean algorithm with k=8

In [2]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in c:\users\augustin\appdata\local\programs\python\python310\lib\site-packages (1.23.3)

WARNING: You are using pip version 22.0.3; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Users\Augustin\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: pandas in c:\users\augustin\appdata\local\programs\python\python310\lib\site-packages (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\augustin\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\augustin\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.23.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\augustin\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2022.2.1)
Requirement already satisfied: six>=1.5 in c:\users\augustin\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

WARNING: You are using pip version 22.0.3; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Users\Augustin\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [3]:
import numpy as np
import pandas as pd

In [5]:
stock_data = pd.read_csv(open("data.csv"))

In [6]:
stock_data

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
0,American Express,-4.755700,4.005090,3.581550,-0.395257,0.768624,1.125940,-0.237274,-1.917280,0.706794,...,4.638010,1.468980,2.748090,-0.022868,1.877090,-0.702470,2.448040,-3.137520,-1.138630,-0.065175
1,Boeing,-3.201900,5.654880,-1.449280,0.693878,0.574788,1.505610,-1.425660,0.467675,-2.908530,...,0.936330,0.122649,3.740370,-0.924520,4.339170,3.060930,4.882840,-0.069109,-0.353045,1.157210
2,Chevron,-0.553840,1.927910,0.529256,1.804510,2.056760,-0.869652,-3.189360,3.371730,3.670840,...,2.067070,1.050500,3.030010,1.437230,2.811480,3.473630,-0.512765,2.892270,-0.832930,0.903809
3,Cisco Systems,0.431862,3.484940,-1.724140,-1.843320,0.304692,-1.122850,-3.839640,0.053079,-3.761930,...,1.289400,3.762490,0.355450,-1.181530,-0.346021,5.351170,2.542790,-0.480513,-3.707930,-2.356270
4,DuPont,3.819160,1.975220,0.000000,1.995930,1.565220,-0.919448,-1.009920,2.828800,-0.357277,...,3.105590,-0.180180,3.002950,-0.645518,0.557621,4.745760,-0.579421,-1.601460,-3.694940,-2.382390
5,Kraft,-2.739730,0.418535,1.119400,0.829346,-0.629111,1.650940,5.137090,0.782524,-1.650270,...,1.391140,-0.126143,2.017110,-0.754243,1.559450,2.161810,-1.794710,3.222660,3.194320,-0.191022
6,Caterpillar,3.203540,5.648110,-1.454610,3.268210,3.257650,-1.011040,-2.554080,2.220930,2.407640,...,0.858277,-3.454950,3.637050,0.311526,2.048640,3.599290,-0.688705,-2.727450,-4.034300,-1.497450
7,Bank of America,-4.561400,-0.324675,-2.607230,-0.372578,1.918050,-1.928370,-5.037040,-0.135410,-1.542780,...,7.621740,0.597015,-2.223990,-1.051160,-6.056340,4.230490,2.888090,-1.251740,-2.850160,-5.503980
8,Verizon,2.150230,1.915300,-0.295223,2.751070,-0.217687,0.794777,0.264901,0.853759,0.279799,...,-2.982220,-2.102260,-1.835110,0.055463,1.718490,1.879910,-0.360510,-0.745033,-0.053648,-1.215380
9,Microsoft,-0.963597,1.408450,-1.883010,-0.701481,2.271790,1.975620,-3.130970,-0.514706,-2.706940,...,0.354610,2.436150,1.673310,-2.772570,1.747420,0.000000,1.960780,-0.858850,-2.984500,-0.497159
10,IBM,2.438550,1.747690,0.206113,1.689980,-0.593472,0.000000,1.694810,0.401998,-3.270040,...,2.040820,-0.225033,2.210880,-0.326435,2.879980,3.028020,0.489097,-0.788653,0.908605,3.791220
11,The Home Depot,0.658256,-1.223080,0.981194,0.266951,0.000000,3.197850,1.922560,2.695490,-2.491870,...,5.064400,-0.053362,0.265252,0.188425,3.113810,-0.888769,-2.329550,-5.648850,0.216626,1.501250
12,Walt Disney,-1.992940,1.794990,0.581677,-0.787219,0.899149,-1.527310,-0.574713,0.856680,-3.306750,...,0.717765,-2.589220,3.173050,1.231990,3.642060,4.277660,4.531000,0.280177,-4.155120,1.714870
13,Procter & Gamble,-2.579670,2.885230,1.050100,1.637200,-0.898204,0.061872,3.482750,-0.771605,-0.720839,...,1.754660,-0.434293,-0.628239,-1.226110,-0.131234,-1.149960,0.170834,-1.396520,2.972430,0.396040
14,Alcoa,1.638310,0.354191,-4.352940,1.984820,3.258150,-3.727930,-8.527130,-0.632547,1.003130,...,-4.428490,2.870260,3.728610,-1.368230,4.334550,5.933250,3.792670,-1.766780,-0.349650,-2.470660
15,Intel,2.044700,8.329430,-0.428816,-3.522500,-3.097730,-1.119930,-1.594420,2.357840,-3.533400,...,1.786580,1.162200,9.882230,-0.873563,2.361810,0.603248,-1.665870,-0.410023,1.210550,-0.998573
16,Hewlett-Packard,-2.527310,-1.680470,-10.497500,-3.394630,3.878580,-0.370054,-1.105380,0.454076,0.024207,...,3.098530,0.123001,2.577580,-1.045050,1.624850,4.448360,6.797730,-10.279600,-0.931601,2.362380
17,Wal-Mart,2.365050,2.574630,-0.575436,-0.344102,-0.364299,-0.170100,1.922340,0.217155,-1.585480,...,2.162160,0.439686,0.941974,0.618357,1.198530,-0.744021,-0.276600,-3.828280,1.364380,1.125020
18,General Electric,1.354740,1.539230,-1.158690,2.675420,0.621118,0.983069,-0.988142,-0.325430,-3.557110,...,1.128430,-2.604920,0.910470,-2.768500,0.355691,2.136120,-0.324500,-0.287356,-0.400601,4.004210
19,AT&T,-3.408290,1.467230,0.000000,5.513440,0.935484,1.618230,-0.325203,0.598592,-1.341810,...,-0.385424,-0.097593,0.854701,-1.168140,0.278067,2.005840,-2.796500,-0.670904,0.673077,-0.770578
20,Merck,-2.706680,6.676560,0.000000,1.628760,-1.254430,1.027690,2.464370,-0.363967,-1.815380,...,-8.132040,0.989802,-0.467836,2.670810,1.495790,-1.201560,2.920910,-1.709920,2.686240,-0.498973
21,Pfizer,-0.981997,5.112780,-0.719770,-0.195886,2.147390,0.896414,-0.097324,1.965990,3.753210,...,0.658617,-0.437956,-2.608270,3.746700,0.147638,6.102250,3.615820,-0.105932,1.899660,0.054496
22,United Technologies,1.457760,2.965520,-1.085240,1.874630,-0.092582,1.989870,-1.823530,-0.070530,-0.718355,...,1.034880,-0.992295,5.447940,-0.861450,2.730630,0.880196,-0.138906,-1.383960,0.112511,1.160440
23,ExxonMobil,0.177552,1.958510,1.682870,0.977820,3.004240,-1.225000,-1.931360,3.048780,-1.004040,...,3.607080,2.005700,3.910480,-0.919995,2.137540,4.204200,2.536630,0.435448,-2.578000,1.529760
24,Travelers,1.215090,3.196350,-0.431862,1.049250,-0.356333,-2.029770,-0.083542,3.535010,-0.701214,...,2.842620,-0.417851,3.371540,-0.704698,0.924025,2.866870,-4.920660,-1.650160,-1.423380,0.695716
25,JPMorgan Chase,-1.481970,2.194850,0.372353,0.542299,0.919811,-1.186730,-4.489360,4.347830,0.704535,...,3.790150,1.561140,0.926135,-2.755820,-0.907519,0.405314,1.488370,-1.101690,-3.575420,0.599733
26,McDonalds,-1.306400,1.503560,2.349580,0.582396,0.110389,2.598530,1.615230,0.078875,-4.086730,...,-0.255892,-0.353820,0.026011,2.039990,2.380950,0.338753,-3.540860,-1.988150,1.610870,0.482251
27,Coca-Cola,-1.049790,-0.721118,0.293686,3.098160,-1.597870,0.798771,1.130110,1.382130,-2.548960,...,0.685805,0.074383,0.458783,1.620690,3.310630,0.385109,-4.493020,1.499370,1.974270,-0.696092
28,3M,-1.984080,3.514000,-2.072430,0.768232,1.278580,0.702216,-0.822737,1.351940,-2.444910,...,2.800470,0.582650,2.153580,0.315560,2.215580,0.409417,-0.599424,-2.674430,0.745016,1.650730
29,Johnson & Johnson,-4.076090,3.252160,-1.084170,0.864700,2.423680,-0.045235,1.713130,0.692042,-1.546480,...,0.417402,-0.067227,5.988420,1.885530,0.528379,1.130320,-0.047900,-1.713910,2.319150,0.723356

In [38]:
from sklearn.cluster import KMeans
kmeans = KMeans(init='random',n_clusters=8)

In [10]:
stock_data2 = stock_data.copy()

In [11]:
stock_data2 = stock_data2.drop("StockName",axis=1)

In [39]:
kmeans.fit(stock_data2)

KMeans(init='random')

In [40]:
kmeans.labels_

array([5, 5, 6, 0, 5, 7, 5, 2, 7, 1, 7, 7, 5, 7, 1, 5, 3, 7, 4, 4, 7, 7,
       5, 6, 5, 6, 7, 7, 5, 5])

In [41]:
stock_data[kmeans.labels_==0]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
3,Cisco Systems,0.431862,3.48494,-1.72414,-1.84332,0.304692,-1.12285,-3.83964,0.053079,-3.76193,...,1.2894,3.76249,0.35545,-1.18153,-0.346021,5.35117,2.54279,-0.480513,-3.70793,-2.35627

In [42]:
stock_data[kmeans.labels_==1]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
9,Microsoft,-0.963597,1.408450,-1.88301,-0.701481,2.27179,1.97562,-3.13097,-0.514706,-2.70694,...,0.35461,2.43615,1.67331,-2.77257,1.74742,0.00000,1.96078,-0.85885,-2.98450,-0.497159
14,Alcoa,1.638310,0.354191,-4.35294,1.984820,3.25815,-3.72793,-8.52713,-0.632547,1.00313,...,-4.42849,2.87026,3.72861,-1.36823,4.33455,5.93325,3.79267,-1.76678,-0.34965,-2.470660

In [43]:
stock_data[kmeans.labels_==2]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
7,Bank of America,-4.5614,-0.324675,-2.60723,-0.372578,1.91805,-1.92837,-5.03704,-0.13541,-1.54278,...,7.62174,0.597015,-2.22399,-1.05116,-6.05634,4.23049,2.88809,-1.25174,-2.85016,-5.50398

In [44]:
stock_data[kmeans.labels_==3]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
16,Hewlett-Packard,-2.52731,-1.68047,-10.4975,-3.39463,3.87858,-0.370054,-1.10538,0.454076,0.024207,...,3.09853,0.123001,2.57758,-1.04505,1.62485,4.44836,6.79773,-10.2796,-0.931601,2.36238

In [45]:
stock_data[kmeans.labels_==4]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
18,General Electric,1.35474,1.53923,-1.15869,2.67542,0.621118,0.983069,-0.988142,-0.325430,-3.55711,...,1.128430,-2.604920,0.910470,-2.76850,0.355691,2.13612,-0.3245,-0.287356,-0.400601,4.004210
19,AT&T,-3.40829,1.46723,0.00000,5.51344,0.935484,1.618230,-0.325203,0.598592,-1.34181,...,-0.385424,-0.097593,0.854701,-1.16814,0.278067,2.00584,-2.7965,-0.670904,0.673077,-0.770578

In [46]:
stock_data[kmeans.labels_==5]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
0,American Express,-4.75570,4.00509,3.581550,-0.395257,0.768624,1.125940,-0.237274,-1.917280,0.706794,...,4.638010,1.468980,2.74809,-0.022868,1.877090,-0.702470,2.448040,-3.137520,-1.138630,-0.065175
1,Boeing,-3.20190,5.65488,-1.449280,0.693878,0.574788,1.505610,-1.425660,0.467675,-2.908530,...,0.936330,0.122649,3.74037,-0.924520,4.339170,3.060930,4.882840,-0.069109,-0.353045,1.157210
4,DuPont,3.81916,1.97522,0.000000,1.995930,1.565220,-0.919448,-1.009920,2.828800,-0.357277,...,3.105590,-0.180180,3.00295,-0.645518,0.557621,4.745760,-0.579421,-1.601460,-3.694940,-2.382390
6,Caterpillar,3.20354,5.64811,-1.454610,3.268210,3.257650,-1.011040,-2.554080,2.220930,2.407640,...,0.858277,-3.454950,3.63705,0.311526,2.048640,3.599290,-0.688705,-2.727450,-4.034300,-1.497450
12,Walt Disney,-1.99294,1.79499,0.581677,-0.787219,0.899149,-1.527310,-0.574713,0.856680,-3.306750,...,0.717765,-2.589220,3.17305,1.231990,3.642060,4.277660,4.531000,0.280177,-4.155120,1.714870
15,Intel,2.04470,8.32943,-0.428816,-3.522500,-3.097730,-1.119930,-1.594420,2.357840,-3.533400,...,1.786580,1.162200,9.88223,-0.873563,2.361810,0.603248,-1.665870,-0.410023,1.210550,-0.998573
22,United Technologies,1.45776,2.96552,-1.085240,1.874630,-0.092582,1.989870,-1.823530,-0.070530,-0.718355,...,1.034880,-0.992295,5.44794,-0.861450,2.730630,0.880196,-0.138906,-1.383960,0.112511,1.160440
24,Travelers,1.21509,3.19635,-0.431862,1.049250,-0.356333,-2.029770,-0.083542,3.535010,-0.701214,...,2.842620,-0.417851,3.37154,-0.704698,0.924025,2.866870,-4.920660,-1.650160,-1.423380,0.695716
28,3M,-1.98408,3.51400,-2.072430,0.768232,1.278580,0.702216,-0.822737,1.351940,-2.444910,...,2.800470,0.582650,2.15358,0.315560,2.215580,0.409417,-0.599424,-2.674430,0.745016,1.650730
29,Johnson & Johnson,-4.07609,3.25216,-1.084170,0.864700,2.423680,-0.045235,1.713130,0.692042,-1.546480,...,0.417402,-0.067227,5.98842,1.885530,0.528379,1.130320,-0.047900,-1.713910,2.319150,0.723356

In [47]:
stock_data[kmeans.labels_==6]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
2,Chevron,-0.553840,1.92791,0.529256,1.804510,2.056760,-0.869652,-3.18936,3.37173,3.670840,...,2.06707,1.05050,3.030010,1.437230,2.811480,3.473630,-0.512765,2.892270,-0.83293,0.903809
23,ExxonMobil,0.177552,1.95851,1.682870,0.977820,3.004240,-1.225000,-1.93136,3.04878,-1.004040,...,3.60708,2.00570,3.910480,-0.919995,2.137540,4.204200,2.536630,0.435448,-2.57800,1.529760
25,JPMorgan Chase,-1.481970,2.19485,0.372353,0.542299,0.919811,-1.186730,-4.48936,4.34783,0.704535,...,3.79015,1.56114,0.926135,-2.755820,-0.907519,0.405314,1.488370,-1.101690,-3.57542,0.599733

In [48]:
stock_data[kmeans.labels_==7]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
5,Kraft,-2.739730,0.418535,1.119400,0.829346,-0.629111,1.650940,5.137090,0.782524,-1.650270,...,1.391140,-0.126143,2.017110,-0.754243,1.559450,2.161810,-1.794710,3.222660,3.194320,-0.191022
8,Verizon,2.150230,1.915300,-0.295223,2.751070,-0.217687,0.794777,0.264901,0.853759,0.279799,...,-2.982220,-2.102260,-1.835110,0.055463,1.718490,1.879910,-0.360510,-0.745033,-0.053648,-1.215380
10,IBM,2.438550,1.747690,0.206113,1.689980,-0.593472,0.000000,1.694810,0.401998,-3.270040,...,2.040820,-0.225033,2.210880,-0.326435,2.879980,3.028020,0.489097,-0.788653,0.908605,3.791220
11,The Home Depot,0.658256,-1.223080,0.981194,0.266951,0.000000,3.197850,1.922560,2.695490,-2.491870,...,5.064400,-0.053362,0.265252,0.188425,3.113810,-0.888769,-2.329550,-5.648850,0.216626,1.501250
13,Procter & Gamble,-2.579670,2.885230,1.050100,1.637200,-0.898204,0.061872,3.482750,-0.771605,-0.720839,...,1.754660,-0.434293,-0.628239,-1.226110,-0.131234,-1.149960,0.170834,-1.396520,2.972430,0.396040
17,Wal-Mart,2.365050,2.574630,-0.575436,-0.344102,-0.364299,-0.170100,1.922340,0.217155,-1.585480,...,2.162160,0.439686,0.941974,0.618357,1.198530,-0.744021,-0.276600,-3.828280,1.364380,1.125020
20,Merck,-2.706680,6.676560,0.000000,1.628760,-1.254430,1.027690,2.464370,-0.363967,-1.815380,...,-8.132040,0.989802,-0.467836,2.670810,1.495790,-1.201560,2.920910,-1.709920,2.686240,-0.498973
21,Pfizer,-0.981997,5.112780,-0.719770,-0.195886,2.147390,0.896414,-0.097324,1.965990,3.753210,...,0.658617,-0.437956,-2.608270,3.746700,0.147638,6.102250,3.615820,-0.105932,1.899660,0.054496
26,McDonalds,-1.306400,1.503560,2.349580,0.582396,0.110389,2.598530,1.615230,0.078875,-4.086730,...,-0.255892,-0.353820,0.026011,2.039990,2.380950,0.338753,-3.540860,-1.988150,1.610870,0.482251
27,Coca-Cola,-1.049790,-0.721118,0.293686,3.098160,-1.597870,0.798771,1.130110,1.382130,-2.548960,...,0.685805,0.074383,0.458783,1.620690,3.310630,0.385109,-4.493020,1.499370,1.974270,-0.696092

Computing the SSE

In [49]:
kmeans.inertia_

1718.2701723705177

### Question 2

trying to decrease SSE with k constant

n_init : increasing it will decrease SSE

In [59]:
kmeans_1 = KMeans(init='random',n_init= 100,n_clusters=8)
kmeans_1.fit(stock_data2)
kmeans_1.inertia_

1668.5361213974677

this is what we observe to a certain extent (till 3000) 1560 seems to be the best value we can get

In [ ]:
kmeans_1 = KMeans(init='random',n_init= 100,n_clusters=8)
kmeans_1.fit(stock_data2)
kmeans_1.inertia_

### Question 3

trying to label each cluster with a topic

In [60]:
kmeans_1 = KMeans(init='random',n_init= 1000,n_clusters=8)
kmeans_1.fit(stock_data2)

KMeans(init='random', n_init=1000)

Cluster 0:

"technologies de pointe"

In [70]:
stock_data[kmeans_1.labels_==0]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
1,Boeing,-3.201900,5.65488,-1.449280,0.693878,0.574788,1.505610,-1.425660,0.467675,-2.908530,...,0.936330,0.122649,3.74037,-0.924520,4.339170,3.060930,4.882840,-0.069109,-0.353045,1.157210
9,Microsoft,-0.963597,1.40845,-1.883010,-0.701481,2.271790,1.975620,-3.130970,-0.514706,-2.706940,...,0.354610,2.436150,1.67331,-2.772570,1.747420,0.000000,1.960780,-0.858850,-2.984500,-0.497159
12,Walt Disney,-1.992940,1.79499,0.581677,-0.787219,0.899149,-1.527310,-0.574713,0.856680,-3.306750,...,0.717765,-2.589220,3.17305,1.231990,3.642060,4.277660,4.531000,0.280177,-4.155120,1.714870
15,Intel,2.044700,8.32943,-0.428816,-3.522500,-3.097730,-1.119930,-1.594420,2.357840,-3.533400,...,1.786580,1.162200,9.88223,-0.873563,2.361810,0.603248,-1.665870,-0.410023,1.210550,-0.998573
22,United Technologies,1.457760,2.96552,-1.085240,1.874630,-0.092582,1.989870,-1.823530,-0.070530,-0.718355,...,1.034880,-0.992295,5.44794,-0.861450,2.730630,0.880196,-0.138906,-1.383960,0.112511,1.160440
24,Travelers,1.215090,3.19635,-0.431862,1.049250,-0.356333,-2.029770,-0.083542,3.535010,-0.701214,...,2.842620,-0.417851,3.37154,-0.704698,0.924025,2.866870,-4.920660,-1.650160,-1.423380,0.695716
28,3M,-1.984080,3.51400,-2.072430,0.768232,1.278580,0.702216,-0.822737,1.351940,-2.444910,...,2.800470,0.582650,2.15358,0.315560,2.215580,0.409417,-0.599424,-2.674430,0.745016,1.650730
29,Johnson & Johnson,-4.076090,3.25216,-1.084170,0.864700,2.423680,-0.045235,1.713130,0.692042,-1.546480,...,0.417402,-0.067227,5.98842,1.885530,0.528379,1.130320,-0.047900,-1.713910,2.319150,0.723356

Cluster 1:

"telecom"

In [71]:
stock_data[kmeans_1.labels_==1]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
3,Cisco Systems,0.431862,3.48494,-1.72414,-1.84332,0.304692,-1.12285,-3.83964,0.053079,-3.76193,...,1.2894,3.76249,0.35545,-1.18153,-0.346021,5.35117,2.54279,-0.480513,-3.70793,-2.35627

Cluster 2:

"industrie pharma"

In [72]:
stock_data[kmeans_1.labels_==2]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
20,Merck,-2.70668,6.67656,0.0,1.62876,-1.25443,1.02769,2.46437,-0.363967,-1.81538,...,-8.13204,0.989802,-0.467836,2.67081,1.49579,-1.20156,2.92091,-1.70992,2.68624,-0.498973

Cluster 3:

"construction"

In [73]:
stock_data[kmeans_1.labels_==3]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
4,DuPont,3.81916,1.975220,0.00000,1.99593,1.56522,-0.919448,-1.00992,2.828800,-0.357277,...,3.105590,-0.18018,3.00295,-0.645518,0.557621,4.74576,-0.579421,-1.60146,-3.69494,-2.38239
6,Caterpillar,3.20354,5.648110,-1.45461,3.26821,3.25765,-1.011040,-2.55408,2.220930,2.407640,...,0.858277,-3.45495,3.63705,0.311526,2.048640,3.59929,-0.688705,-2.72745,-4.03430,-1.49745
14,Alcoa,1.63831,0.354191,-4.35294,1.98482,3.25815,-3.727930,-8.52713,-0.632547,1.003130,...,-4.428490,2.87026,3.72861,-1.368230,4.334550,5.93325,3.792670,-1.76678,-0.34965,-2.47066

Cluster 4:

"informatique"

In [74]:
stock_data[kmeans_1.labels_==4]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
16,Hewlett-Packard,-2.52731,-1.68047,-10.4975,-3.39463,3.87858,-0.370054,-1.10538,0.454076,0.024207,...,3.09853,0.123001,2.57758,-1.04505,1.62485,4.44836,6.79773,-10.2796,-0.931601,2.36238

Cluster 5:
    
"service au particulier"

In [75]:
stock_data[kmeans_1.labels_==5]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
5,Kraft,-2.739730,0.418535,1.119400,0.829346,-0.629111,1.650940,5.137090,0.782524,-1.650270,...,1.391140,-0.126143,2.017110,-0.754243,1.559450,2.161810,-1.794710,3.222660,3.194320,-0.191022
8,Verizon,2.150230,1.915300,-0.295223,2.751070,-0.217687,0.794777,0.264901,0.853759,0.279799,...,-2.982220,-2.102260,-1.835110,0.055463,1.718490,1.879910,-0.360510,-0.745033,-0.053648,-1.215380
10,IBM,2.438550,1.747690,0.206113,1.689980,-0.593472,0.000000,1.694810,0.401998,-3.270040,...,2.040820,-0.225033,2.210880,-0.326435,2.879980,3.028020,0.489097,-0.788653,0.908605,3.791220
11,The Home Depot,0.658256,-1.223080,0.981194,0.266951,0.000000,3.197850,1.922560,2.695490,-2.491870,...,5.064400,-0.053362,0.265252,0.188425,3.113810,-0.888769,-2.329550,-5.648850,0.216626,1.501250
13,Procter & Gamble,-2.579670,2.885230,1.050100,1.637200,-0.898204,0.061872,3.482750,-0.771605,-0.720839,...,1.754660,-0.434293,-0.628239,-1.226110,-0.131234,-1.149960,0.170834,-1.396520,2.972430,0.396040
17,Wal-Mart,2.365050,2.574630,-0.575436,-0.344102,-0.364299,-0.170100,1.922340,0.217155,-1.585480,...,2.162160,0.439686,0.941974,0.618357,1.198530,-0.744021,-0.276600,-3.828280,1.364380,1.125020
18,General Electric,1.354740,1.539230,-1.158690,2.675420,0.621118,0.983069,-0.988142,-0.325430,-3.557110,...,1.128430,-2.604920,0.910470,-2.768500,0.355691,2.136120,-0.324500,-0.287356,-0.400601,4.004210
19,AT&T,-3.408290,1.467230,0.000000,5.513440,0.935484,1.618230,-0.325203,0.598592,-1.341810,...,-0.385424,-0.097593,0.854701,-1.168140,0.278067,2.005840,-2.796500,-0.670904,0.673077,-0.770578
26,McDonalds,-1.306400,1.503560,2.349580,0.582396,0.110389,2.598530,1.615230,0.078875,-4.086730,...,-0.255892,-0.353820,0.026011,2.039990,2.380950,0.338753,-3.540860,-1.988150,1.610870,0.482251
27,Coca-Cola,-1.049790,-0.721118,0.293686,3.098160,-1.597870,0.798771,1.130110,1.382130,-2.548960,...,0.685805,0.074383,0.458783,1.620690,3.310630,0.385109,-4.493020,1.499370,1.974270,-0.696092

Cluster 6:
    
"banque"

In [76]:
stock_data[kmeans_1.labels_==6]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
0,American Express,-4.75570,4.005090,3.581550,-0.395257,0.768624,1.12594,-0.237274,-1.91728,0.706794,...,4.63801,1.468980,2.748090,-0.022868,1.877090,-0.702470,2.44804,-3.13752,-1.13863,-0.065175
7,Bank of America,-4.56140,-0.324675,-2.607230,-0.372578,1.918050,-1.92837,-5.037040,-0.13541,-1.542780,...,7.62174,0.597015,-2.223990,-1.051160,-6.056340,4.230490,2.88809,-1.25174,-2.85016,-5.503980
25,JPMorgan Chase,-1.48197,2.194850,0.372353,0.542299,0.919811,-1.18673,-4.489360,4.34783,0.704535,...,3.79015,1.561140,0.926135,-2.755820,-0.907519,0.405314,1.48837,-1.10169,-3.57542,0.599733

Cluster 7:

"petrochimie"

In [77]:
stock_data[kmeans_1.labels_==7]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
2,Chevron,-0.553840,1.92791,0.529256,1.804510,2.05676,-0.869652,-3.189360,3.37173,3.67084,...,2.067070,1.050500,3.03001,1.437230,2.811480,3.47363,-0.512765,2.892270,-0.83293,0.903809
21,Pfizer,-0.981997,5.11278,-0.719770,-0.195886,2.14739,0.896414,-0.097324,1.96599,3.75321,...,0.658617,-0.437956,-2.60827,3.746700,0.147638,6.10225,3.615820,-0.105932,1.89966,0.054496
23,ExxonMobil,0.177552,1.95851,1.682870,0.977820,3.00424,-1.225000,-1.931360,3.04878,-1.00404,...,3.607080,2.005700,3.91048,-0.919995,2.137540,4.20420,2.536630,0.435448,-2.57800,1.529760

### Question 4

Kmeans++

In [83]:
kmeans_plus = KMeans(n_init=50,n_clusters=8)
kmeans_plus.fit(stock_data2)
kmeans_plus.inertia_

1528.5255902412098

In [84]:
stock_data[kmeans_plus.labels_==0]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
0,American Express,-4.755700,4.00509,3.581550,-0.395257,0.768624,1.125940,-0.237274,-1.917280,0.706794,...,4.638010,1.468980,2.748090,-0.022868,1.877090,-0.702470,2.448040,-3.137520,-1.138630,-0.065175
1,Boeing,-3.201900,5.65488,-1.449280,0.693878,0.574788,1.505610,-1.425660,0.467675,-2.908530,...,0.936330,0.122649,3.740370,-0.924520,4.339170,3.060930,4.882840,-0.069109,-0.353045,1.157210
9,Microsoft,-0.963597,1.40845,-1.883010,-0.701481,2.271790,1.975620,-3.130970,-0.514706,-2.706940,...,0.354610,2.436150,1.673310,-2.772570,1.747420,0.000000,1.960780,-0.858850,-2.984500,-0.497159
10,IBM,2.438550,1.74769,0.206113,1.689980,-0.593472,0.000000,1.694810,0.401998,-3.270040,...,2.040820,-0.225033,2.210880,-0.326435,2.879980,3.028020,0.489097,-0.788653,0.908605,3.791220
12,Walt Disney,-1.992940,1.79499,0.581677,-0.787219,0.899149,-1.527310,-0.574713,0.856680,-3.306750,...,0.717765,-2.589220,3.173050,1.231990,3.642060,4.277660,4.531000,0.280177,-4.155120,1.714870
18,General Electric,1.354740,1.53923,-1.158690,2.675420,0.621118,0.983069,-0.988142,-0.325430,-3.557110,...,1.128430,-2.604920,0.910470,-2.768500,0.355691,2.136120,-0.324500,-0.287356,-0.400601,4.004210
22,United Technologies,1.457760,2.96552,-1.085240,1.874630,-0.092582,1.989870,-1.823530,-0.070530,-0.718355,...,1.034880,-0.992295,5.447940,-0.861450,2.730630,0.880196,-0.138906,-1.383960,0.112511,1.160440
24,Travelers,1.215090,3.19635,-0.431862,1.049250,-0.356333,-2.029770,-0.083542,3.535010,-0.701214,...,2.842620,-0.417851,3.371540,-0.704698,0.924025,2.866870,-4.920660,-1.650160,-1.423380,0.695716
25,JPMorgan Chase,-1.481970,2.19485,0.372353,0.542299,0.919811,-1.186730,-4.489360,4.347830,0.704535,...,3.790150,1.561140,0.926135,-2.755820,-0.907519,0.405314,1.488370,-1.101690,-3.575420,0.599733
28,3M,-1.984080,3.51400,-2.072430,0.768232,1.278580,0.702216,-0.822737,1.351940,-2.444910,...,2.800470,0.582650,2.153580,0.315560,2.215580,0.409417,-0.599424,-2.674430,0.745016,1.650730
29,Johnson & Johnson,-4.076090,3.25216,-1.084170,0.864700,2.423680,-0.045235,1.713130,0.692042,-1.546480,...,0.417402,-0.067227,5.988420,1.885530,0.528379,1.130320,-0.047900,-1.713910,2.319150,0.723356

In [85]:
stock_data[kmeans_plus.labels_==1]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
2,Chevron,-0.553840,1.92791,0.529256,1.804510,2.05676,-0.869652,-3.189360,3.37173,3.67084,...,2.067070,1.050500,3.03001,1.437230,2.811480,3.47363,-0.512765,2.892270,-0.83293,0.903809
21,Pfizer,-0.981997,5.11278,-0.719770,-0.195886,2.14739,0.896414,-0.097324,1.96599,3.75321,...,0.658617,-0.437956,-2.60827,3.746700,0.147638,6.10225,3.615820,-0.105932,1.89966,0.054496
23,ExxonMobil,0.177552,1.95851,1.682870,0.977820,3.00424,-1.225000,-1.931360,3.04878,-1.00404,...,3.607080,2.005700,3.91048,-0.919995,2.137540,4.20420,2.536630,0.435448,-2.57800,1.529760

In [86]:
stock_data[kmeans_plus.labels_==2]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
5,Kraft,-2.739730,0.418535,1.119400,0.829346,-0.629111,1.650940,5.137090,0.782524,-1.650270,...,1.391140,-0.126143,2.017110,-0.754243,1.559450,2.161810,-1.794710,3.222660,3.194320,-0.191022
8,Verizon,2.150230,1.915300,-0.295223,2.751070,-0.217687,0.794777,0.264901,0.853759,0.279799,...,-2.982220,-2.102260,-1.835110,0.055463,1.718490,1.879910,-0.360510,-0.745033,-0.053648,-1.215380
11,The Home Depot,0.658256,-1.223080,0.981194,0.266951,0.000000,3.197850,1.922560,2.695490,-2.491870,...,5.064400,-0.053362,0.265252,0.188425,3.113810,-0.888769,-2.329550,-5.648850,0.216626,1.501250
13,Procter & Gamble,-2.579670,2.885230,1.050100,1.637200,-0.898204,0.061872,3.482750,-0.771605,-0.720839,...,1.754660,-0.434293,-0.628239,-1.226110,-0.131234,-1.149960,0.170834,-1.396520,2.972430,0.396040
17,Wal-Mart,2.365050,2.574630,-0.575436,-0.344102,-0.364299,-0.170100,1.922340,0.217155,-1.585480,...,2.162160,0.439686,0.941974,0.618357,1.198530,-0.744021,-0.276600,-3.828280,1.364380,1.125020
19,AT&T,-3.408290,1.467230,0.000000,5.513440,0.935484,1.618230,-0.325203,0.598592,-1.341810,...,-0.385424,-0.097593,0.854701,-1.168140,0.278067,2.005840,-2.796500,-0.670904,0.673077,-0.770578
20,Merck,-2.706680,6.676560,0.000000,1.628760,-1.254430,1.027690,2.464370,-0.363967,-1.815380,...,-8.132040,0.989802,-0.467836,2.670810,1.495790,-1.201560,2.920910,-1.709920,2.686240,-0.498973
26,McDonalds,-1.306400,1.503560,2.349580,0.582396,0.110389,2.598530,1.615230,0.078875,-4.086730,...,-0.255892,-0.353820,0.026011,2.039990,2.380950,0.338753,-3.540860,-1.988150,1.610870,0.482251
27,Coca-Cola,-1.049790,-0.721118,0.293686,3.098160,-1.597870,0.798771,1.130110,1.382130,-2.548960,...,0.685805,0.074383,0.458783,1.620690,3.310630,0.385109,-4.493020,1.499370,1.974270,-0.696092

In [89]:
stock_data[kmeans_plus.labels_==3]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
7,Bank of America,-4.5614,-0.324675,-2.60723,-0.372578,1.91805,-1.92837,-5.03704,-0.13541,-1.54278,...,7.62174,0.597015,-2.22399,-1.05116,-6.05634,4.23049,2.88809,-1.25174,-2.85016,-5.50398

In [90]:
stock_data[kmeans_plus.labels_==4]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
16,Hewlett-Packard,-2.52731,-1.68047,-10.4975,-3.39463,3.87858,-0.370054,-1.10538,0.454076,0.024207,...,3.09853,0.123001,2.57758,-1.04505,1.62485,4.44836,6.79773,-10.2796,-0.931601,2.36238

In [91]:
stock_data[kmeans_plus.labels_==5]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
3,Cisco Systems,0.431862,3.48494,-1.72414,-1.84332,0.304692,-1.12285,-3.83964,0.053079,-3.76193,...,1.2894,3.76249,0.35545,-1.18153,-0.346021,5.35117,2.54279,-0.480513,-3.70793,-2.35627

In [92]:
stock_data[kmeans_plus.labels_==6]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
4,DuPont,3.81916,1.975220,0.00000,1.99593,1.56522,-0.919448,-1.00992,2.828800,-0.357277,...,3.105590,-0.18018,3.00295,-0.645518,0.557621,4.74576,-0.579421,-1.60146,-3.69494,-2.38239
6,Caterpillar,3.20354,5.648110,-1.45461,3.26821,3.25765,-1.011040,-2.55408,2.220930,2.407640,...,0.858277,-3.45495,3.63705,0.311526,2.048640,3.59929,-0.688705,-2.72745,-4.03430,-1.49745
14,Alcoa,1.63831,0.354191,-4.35294,1.98482,3.25815,-3.727930,-8.52713,-0.632547,1.003130,...,-4.428490,2.87026,3.72861,-1.368230,4.334550,5.93325,3.792670,-1.76678,-0.34965,-2.47066

In [93]:
stock_data[kmeans_plus.labels_==7]

,StockName,1/28/2011,4/29/2011,5/20/2011,4/1/2011,5/27/2011,6/17/2011,4/15/2011,2/18/2011,3/18/2011,...,1/14/2011,4/8/2011,4/21/2011,3/4/2011,3/25/2011,2/4/2011,1/7/2011,2/25/2011,5/13/2011,1/21/2011
15,Intel,2.0447,8.32943,-0.428816,-3.5225,-3.09773,-1.11993,-1.59442,2.35784,-3.5334,...,1.78658,1.1622,9.88223,-0.873563,2.36181,0.603248,-1.66587,-0.410023,1.21055,-0.998573